import turtle as t
t.width(10)
t.speed(0)
for i in range(6):
    if i == 0:
        t.penup()
        t.goto(-260,205)
        t.pendown()
    elif i == 1:
        t.penup()
        t.goto(0, 205)
        t.pendown()
def treugolnik(color):
    t.pencolor('black')
    t.fillcolor(color)
    t.begin_fill()
    t.penup()
    t.right(90)
    t.pendown()
    for i in range(3):
        t.fd(120)
        t.right(120)
    t.end_fill()
    t.setheading(90)
def kvadrat(color):
    t.penup()
    t.fd(50)
    t.right(90)
    t.back(50)
    t.pendown()
    t.pencolor('black')
    t.fillcolor(color)
    t.begin_fill()
    t.fd(100)
    t.rt(90)
    t.fd(100)
    t.rt(90)
    t.fd(100)
    t.rt(90)
    t.fd(100)
    t.end_fill()
    t.setheading(90)
def krug(color):
    t.pencolor('black')
    t.fillcolor(color)
    t.begin_fill()
    t.penup()
    t.fd(35)
    t.right(270)
    t.pendown()
    t.circle(70)
    t.end_fill()
    t.setheading(90)